name: Generate and Deploy Docs

on:
  push:
    branches:
      - master

  # This event is required to deploy to GitHub Pages with actions/deploy-pages@v4
  workflow_run:
    workflows: ["Generate and Deploy Docs"]
    types:
      - completed

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: 1.1.29
    
    - name: Install dependencies
      run: bun install

    - name: Build the docs
      run: bun run docs
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        path: ./docs  # Path to the docs folder
  
  deploy-docs:
    runs-on: ubuntu-latest
    needs: generate-docs
    permissions:
      pages: write  # Needed to deploy to GitHub Pages
      id-token: write  # Needed for authentication
      actions: read
    
    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
