name: Generate and Deploy Docs

on:
  push:
    branches:
      - master

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Pages
      id: pages
      uses: actions/configure-pages@v4

    - name: Set up Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: 1.1.29
    
    - name: Install dependencies
      run: bun install

    - name: Build the docs
      run: bun run docs
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        path: ./docs  # Path to the docs folder
  
  deploy-docs:
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    needs: generate-docs
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    steps:
      - name: Deploy artifact
        id: deployment
        uses: actions/deploy-pages@v4
