name: test-workflow

on: push

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    # checkout

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    # bun

    - name: Set up Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Install dependencies
      run: bun install

    - name: Run JavaScript/TypeScript tests
      run: bun run test

    # rust

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        components: rustfmt, clippy

    - name: Build Rust project
      run: cargo build
      shell: bash

    - name: Run Clippy
      run: cargo clippy -- -D warnings
      shell: bash

    - name: Check Formatting
      run: cargo fmt -- --check
      shell: bash

    - name: Run Rust tests with coverage
      run: cargo test --workspace
      shell: bash
